[build]
  command = "# no build command"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["whatsapp-web.js", "puppeteer", "fluent-ffmpeg"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200